dataset_sync_path: /media/fabrizio-berritta/data/databases/2025_SquidLab_AdaptiveT1Pelagic/20250905_adaptive_T1_Q3_Q5/BayesianEstimationDecayRate_152641
dataset_uuid: 4a97077e-cd5c-4f02-b6b6-2cbc631f2d35
errors:
- Failed to update dataset UUID in the database (unique constraint failed), this is
  most likely caused by another sync source that is already synchronizing this dataset.
files:
  analyzed_data.zarr:
    zarr_to_zip_converter:
      m_time: 1758409660.888985
      output: analyzed_data.zarr.zip
      status: OK
  figure.html:
    m_time: '2025-09-04T09:30:45'
    status: OK
  figure.pdf:
    m_time: '2025-09-04T09:30:45'
    status: OK
  figure.png:
    m_time: '2025-09-04T09:30:45'
    status: OK
  figure_1.pdf:
    m_time: '2025-09-04T09:30:46'
    status: OK
  figure_1.png:
    m_time: '2025-09-04T09:30:46'
    status: OK
  program.py:
    m_time: '2025-09-04T09:30:49'
    status: OK
  raw_data.zarr:
    zarr_to_zip_converter:
      m_time: 1758409662.7040305
      output: raw_data.zarr.zip
      status: OK
  state/information.json:
    m_time: '2025-09-04T09:30:48'
    status: OK
  state/network.json:
    m_time: '2025-09-04T09:30:48'
    status: OK
  state/state.json:
    m_time: '2025-09-04T09:30:48'
    status: OK
  state/wiring.json:
    m_time: '2025-09-04T09:30:48'
    status: OK
scope_uuid: 5197d1b6-a2ad-4333-953a-707fd852ced3
sync_time: '2025-10-03T20:56:21.005011'
version: 0.1
